require 'pb_json_parser'

describe PbJsonParser do
  describe ".parse" do
    it "returns parsed result" do
      expect(PbJsonParser.parse(json: json, filename: "resources.proto").map(&:to_h)).to eq [
        {
          name: "User",
          fields: [
            { name: "id",       type: "int64" },
            { name: "number",   type: "int32" },
            { name: "admin",    type: "bool" },
            { name: "name",     type: "string" },
            { name: "score",    type: "float" },
            { name: "priority", type: "double" },
            { name: "size",     type: "uint32" },
            { name: "length",   type: "uint64" },
            { name: "record",   type: "bytes" },
            { name: "flag",     type: ".south37.users_prototype.Flag" },
          ],
          assocs: [
            {
              name:       "profile",
              type:       "has_one",
              class_name: "Profile"
            }
          ]
        },
        {
          name: "Profile",
          fields: [
            { name: "id",       type: "int32" },
            { name: "birthday", type: ".google.protobuf.Timestamp" }
          ],
          assocs: []
        },
      ]

      expect(PbJsonParser.parse(json: json, filename: "resources.proto", skip_fields: ["birthday"]).map(&:to_h)).to eq [
        {
          name: "User",
          fields: [
            { name: "id",     type: "int64" },
            { name: "number", type: "int32" },
            { name: "admin",  type: "bool" },
            { name: "name",   type: "string" },
            { name: "score",    type: "float" },
            { name: "priority", type: "double" },
            { name: "size",     type: "uint32" },
            { name: "length",   type: "uint64" },
            { name: "record",   type: "bytes" },
            { name: "flag",   type: ".south37.users_prototype.Flag" },
          ],
          assocs: [
            {
              name:       "profile",
              type:       "has_one",
              class_name: "Profile"
            }
          ]
        },
        {
          name: "Profile",
          fields: [
            { name: "id", type: "int32" },
          ],
          assocs: []
        },
      ]
    end
  end

  # This json is generated by protoc-gen-json from .proto file below.
  #
  # // resources.proto
  # syntax = "proto3";
  # package south37.users_prototype;
  #
  # import "google/protobuf/timestamp.proto";
  #
  # message User {
  #   int64 id = 1;
  #   int32 number = 2;
  #   bool admin = 3;
  #   string name = 4;
  #   float score = 5;
  #   double priority = 6;
  #   uint32 size = 7;
  #   uint64 length = 8;
  #   bytes record = 9;
  #   Profile profile = 10;
  #   Flag flag = 11;
  # }
  #
  # message Profile {
  #   int32 id = 1;
  #   google.protobuf.Timestamp birthday = 2;
  # }
  #
  # enum Flag {
  #   FLAG_UNSPECIFIED = 0;
  #   ON = 1;
  #   OFF = 2;
  # }
  #
  def json
<<-JSON
{
  "file_to_generate": [
    "resources.proto"
  ],
  "parameter": "out=resources.proto.json",
  "proto_file": [
    {
      "name": "google/protobuf/timestamp.proto",
      "package": "google.protobuf",
      "message_type": [
        {
          "name": "Timestamp",
          "field": [
            {
              "name": "seconds",
              "number": 1,
              "label": 1,
              "type": 3,
              "json_name": "seconds"
            },
            {
              "name": "nanos",
              "number": 2,
              "label": 1,
              "type": 5,
              "json_name": "nanos"
            }
          ]
        }
      ],
      "options": {
        "java_package": "com.google.protobuf",
        "java_outer_classname": "TimestampProto",
        "java_multiple_files": true,
        "go_package": "github.com/golang/protobuf/ptypes/timestamp",
        "cc_enable_arenas": true,
        "objc_class_prefix": "GPB",
        "csharp_namespace": "Google.Protobuf.WellKnownTypes"
      },
      "source_code_info": {
        "location": []
      },
      "syntax": "proto3"
    },
    {
      "name": "resources.proto",
      "package": "south37.users_prototype",
      "dependency": [
        "google/protobuf/timestamp.proto"
      ],
      "message_type": [
        {
          "name": "User",
          "field": [
            {
              "name": "id",
              "number": 1,
              "label": 1,
              "type": 3,
              "json_name": "id"
            },
            {
              "name": "number",
              "number": 2,
              "label": 1,
              "type": 5,
              "json_name": "number"
            },
            {
              "name": "admin",
              "number": 3,
              "label": 1,
              "type": 8,
              "json_name": "admin"
            },
            {
              "name": "name",
              "number": 4,
              "label": 1,
              "type": 9,
              "json_name": "name"
            },
            {
              "name": "score",
              "number": 5,
              "label": 1,
              "type": 2,
              "json_name": "score"
            },
            {
              "name": "priority",
              "number": 6,
              "label": 1,
              "type": 1,
              "json_name": "priority"
            },
            {
              "name": "size",
              "number": 7,
              "label": 1,
              "type": 13,
              "json_name": "size"
            },
            {
              "name": "length",
              "number": 8,
              "label": 1,
              "type": 4,
              "json_name": "length"
            },
            {
              "name": "record",
              "number": 9,
              "label": 1,
              "type": 12,
              "json_name": "record"
            },
            {
              "name": "profile",
              "number": 10,
              "label": 1,
              "type": 11,
              "type_name": ".south37.users_prototype.Profile",
              "json_name": "profile"
            },
            {
              "name": "flag",
              "number": 11,
              "label": 1,
              "type": 14,
              "type_name": ".south37.users_prototype.Flag",
              "json_name": "flag"
            }
          ]
        },
        {
          "name": "Profile",
          "field": [
            {
              "name": "id",
              "number": 1,
              "label": 1,
              "type": 5,
              "json_name": "id"
            },
            {
              "name": "birthday",
              "number": 2,
              "label": 1,
              "type": 11,
              "type_name": ".google.protobuf.Timestamp",
              "json_name": "birthday"
            }
          ]
        }
      ],
      "enum_type": [
        {
          "name": "Flag",
          "value": [
            {
              "name": "FLAG_UNSPECIFIED",
              "number": 0
            },
            {
              "name": "ON",
              "number": 1
            },
            {
              "name": "OFF",
              "number": 2
            }
          ]
        }
      ],
      "source_code_info": {
        "location": []
      },
      "syntax": "proto3"
    }
  ],
  "compiler_version": {
    "major": 3,
    "minor": 5,
    "patch": 1,
    "suffix": ""
  }
}
JSON
  end
end
