require 'pb_json_parser'

describe PbJsonParser do
  describe ".parse" do
    it "returns parsed result" do
      expect(PbJsonParser.parse(json: json, filename: "resources.proto").map(&:to_h)).to eq [
        {
          name: "User",
          fields: [
            "id",
          ],
          assocs: [
            {
              name:       "profile",
              type:       "has_one",
              class_name: "Profile"
            }
          ]
        },
        {
          name: "Profile",
          fields: [
            "id",
            "birthday",
          ],
          assocs: []
        },
      ]

      expect(PbJsonParser.parse(json: json, filename: "resources.proto", skip_fields: ["birthday"]).map(&:to_h)).to eq [
        {
          name: "User",
          fields: [
            "id",
          ],
          assocs: [
            {
              name:       "profile",
              type:       "has_one",
              class_name: "Profile"
            }
          ]
        },
        {
          name: "Profile",
          fields: [
            "id",
          ],
          assocs: []
        },
      ]
    end
  end

  # This json is generated by protoc-gen-json from .proto file below.
  #
  # // resources.proto
  # syntax = "proto3";
  # package south37.users_prototype;
  #
  # import "google/protobuf/timestamp.proto";
  #
  # message User {
  #   int32 id = 1;
  #   Profile profile = 2;
  # }
  #
  # message Profile {
  #   int32 id = 1;
  #   google.protobuf.Timestamp birthday = 2;
  # }
  #
  def json
<<-JSON
{
  "file_to_generate": [
    "resources.proto"
  ],
  "parameter": "out=resources.proto.json",
  "proto_file": [
    {
      "name": "google/protobuf/timestamp.proto",
      "package": "google.protobuf",
      "message_type": [
        {
          "name": "Timestamp",
          "field": [
            {
              "name": "seconds",
              "number": 1,
              "label": 1,
              "type": 3,
              "json_name": "seconds"
            },
            {
              "name": "nanos",
              "number": 2,
              "label": 1,
              "type": 5,
              "json_name": "nanos"
            }
          ]
        }
      ],
      "options": {
        "java_package": "com.google.protobuf",
        "java_outer_classname": "TimestampProto",
        "java_multiple_files": true,
        "go_package": "github.com/golang/protobuf/ptypes/timestamp",
        "cc_enable_arenas": true,
        "objc_class_prefix": "GPB",
        "csharp_namespace": "Google.Protobuf.WellKnownTypes"
      },
      "source_code_info": {
        "location": []
      },
      "syntax": "proto3"
    },
    {
      "name": "resources.proto",
      "package": "south37.users_prototype",
      "dependency": [
        "google/protobuf/timestamp.proto"
      ],
      "message_type": [
        {
          "name": "User",
          "field": [
            {
              "name": "id",
              "number": 1,
              "label": 1,
              "type": 5,
              "json_name": "id"
            },
            {
              "name": "profile",
              "number": 2,
              "label": 1,
              "type": 11,
              "type_name": ".south37.users_prototype.Profile",
              "json_name": "profile"
            }
          ]
        },
        {
          "name": "Profile",
          "field": [
            {
              "name": "id",
              "number": 1,
              "label": 1,
              "type": 5,
              "json_name": "id"
            },
            {
              "name": "birthday",
              "number": 2,
              "label": 1,
              "type": 11,
              "type_name": ".google.protobuf.Timestamp",
              "json_name": "birthday"
            }
          ]
        }
      ],
      "source_code_info": {
        "location": []
      },
      "syntax": "proto3"
    }
  ],
  "compiler_version": {
    "major": 3,
    "minor": 5,
    "patch": 1,
    "suffix": ""
  }
}
JSON
  end
end
